package(default_visibility = ['//visibility:public'])

cc_library(
  name = 'shape_detector_lib',
  srcs = ['shape_detector.cc',],
  hdrs = ['shape_detector.h',],

  deps = [
    '//external:opencv'
  ],
  copts = [
    '-Wno-cast-align',
  ],
)
